config/routes.rb
Rails.application.routes.draw do
  get '/', to: redirect('/addresses/new')

  root 'addresses#new'

  resources :addresses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  validates :zipcode, presence: true

  include HTTParty

  def getLocationKey(zipcode)
    locationKey = HTTParty.get("http://dataservice.accuweather.com/locations/v1/postalcodes/search?apikey=#{AUTH_DETAILS}&q=#{zipcode}")[0]["Key"]
  end

  def getTemps
    locationKey = getLocationKey(zipcode)
    high_and_low = HTTParty.get("http://dataservice.accuweather.com/forecasts/v1/daily/1day/#{locationKey}?apikey=#{AUTH_DETAILS}")["DailyForecasts"][0]["Temperature"]
    high = high_and_low["Maximum"]["Value"]
    low = high_and_low["Minimum"]["Value"]
    current = HTTParty.get("http://dataservice.accuweather.com/currentconditions/v1/#{locationKey}?apikey=#{AUTH_DETAILS}")[0]["Temperature"]["Imperial"]["Value"]
    five = HTTParty.get("http://dataservice.accuweather.com/forecasts/v1/daily/5day/#{locationKey}?apikey=#{AUTH_DETAILS}")
    temps = {high_temp: high, low_temp: low, current_temp: current}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street_and_number, :city, :state, :zipcode)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_form.html.erb
<div class="jumbotron">
  <h1 class="display-3">Welcome to Scott's Weather Forecaster</h1>
</div>

<div class="row">
  <div class="col-md-6 padding-left-3rem">
    <p>Please fill out your address in the form below. The zipcode field is required, but the others are optional.
    Once you submit the form, you will be able to see the current temperature, as well as the forecasted high and
    low temperatures for the day.</p>
  </div>
</div>

<div class="row">
  <div class="col-md-6 padding-left-3rem">
  <%= form_with(model: address, local: true) do |form| %>
    <% if address.errors.any? %>
      <div id="error_explanation">
        <h4><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h4>
        <ul>
        <% address.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :street_and_number %>
      <%= form.text_field :street_and_number %>
    </div>

    <div class="field">
      <%= form.label :city %>
      <%= form.text_field :city %>
    </div>

    <div class="field">
      <%= form.label :state %>
      <%= form.text_field :state %>
    </div>

    <div class="field">
      <%= form.label :zipcode %>
      <%= form.text_field :zipcode %>
    </div>

    <div class="actions">
      <%= form.submit "Get my forecast!"%>
    </div>
  <% end %>
  </div>
</div>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Street and number</th>
      <th>City</th>
      <th>State</th>
      <th>Zipcode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.street_and_number %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= address.zipcode %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<%= render 'form', address: @address %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Here are the details of the weather forecast.</h3>

<p>
  <strong>Street and number:</strong>
  <%= @address.street_and_number %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @address.zipcode %>
</p>

<p>Current Temperature: <%= @address.getTemps[:current_temp] %>° F</p>
<p>Today's High Temperature: <%= @address.getTemps[:high_temp] %>° F</p>
<p>Today's Low Temperature: <%= @address.getTemps[:low_temp] %>° F</p>

<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherByScott</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>